### ISSUE TITLE
AIRSENS_getPress returns 0

### ISSUE THREAD

**Issue by staefy** [danned/projekt#3]
AIRSENS_getPress returnerar 0 när jag försöker använda den i controllern (på min station iaf). 

Case
 int air_reading = AIRSENS_getPress();

air_reading visar noll efter den raden

**Comment by danned** [comment]
Den fungerar bra, kan du ha glömt initen? Mina värden som returneras är ca 101kPa

**Comment by staefy** [comment]
Fungerar på riktiga stationen men inte på min. Closar
