### ISSUE TITLE
Traversing with temp->next - hardfault error

### ISSUE THREAD

**Issue by staefy** [danned/projekt#5]
När jag försöker traversera den länkade listan listan så går det bra fram tills den ska kolla den **sista** där temp->next är undefined. Så fort den jämförelsen kommer så hamnar den i hardfault handler.  

```javascript
node_t *temp = mem.root;
  char count = 0;
  //Get last 7 days worth of data from database
  while(temp->next != NULL && count <7){
	Display_Draw_Graph(&temp->temp, count);
    count++;
    temp = temp->next;
  }
```

Så två rundor går bra! Den ritar ut två dags-grafer. Men sen ska den vara klar för det finns bara två. 
Tror det är något med det att temp->next blir undefined. Men hur kollar man det ordentligt?

**Comment by danned** [comment]
När jag kör denna koden på min dator så skrivs det ut i konsolen iallafall. Men jag kommer inte in i hardfault handler. Ska se om jag kanske borde testa det på stationen 

node_t *temp = mem.root;
    char count = 0;
    //Get last 7 days worth of data from database
    while(temp != NULL && count <7){
        //Display_Draw_Graph(&temp->temp, count);
        printf("max: %d. min: %d. avg: %d\n",MEM_get(temp).max,MEM_get(temp).min,MEM_get(temp).avg);
        count++;
        temp = temp->next;
    }

**Comment by staefy** [comment]
Okej! Jag kanske gör nåt fel. Testa på stationen när du har tid!

**Comment by danned** [comment]
Fungerade bra på stationen för mig, Dock printar jag i terminal

**Comment by staefy** [comment]
Ej utrett men löst med din kod.
