### ISSUE TITLE
temp modul tc block 1

### ISSUE THREAD

**Issue by danned** [danned/projekt#8]
TC block 1 är för tillfället inte aktivt. Inga register påverkas när man försöker sätta dem och räknaren är stilla på 0.
Temp modulen ger därför ett värde av ca -200

**Comment by staefy** [comment]
Den startas som jag skrev i chatten under TC0 i IAR. Något annat är dock fel! I mitt fall där jag saknar temp modul helt blir värdet -273 grader. Är det samma du får? Eller får du -200?

**Comment by danned** [comment]
Problemet låg inte i att blocket inte var aktivt, kollade fel i debuggern. Felet låg i en miss av nollställning av flaggor
